FROM node:24-alpine3.21

COPY . /opt/ 

WORKDIR /opt

RUN npm install && npm run build

RUN apk update && apk add apache2

RUN mkdir -p /var/www/localhost/htdocs
COPY --from=build /opt/dist /var/www/localhost/htdocs

EXPOSE 80

ENTRYPOINT [ "httpd", "-D", "FOREGROUND" ]
